server:
  port: 8762
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: peer2
  client:
    register-with-eureka: true
    fetch-registry: false
  service-url:
    defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/