server:
  port: 8000

spring:
  application:
    name: spring-cloud-provider
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: true
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:                                # 配置日志级别，让hibernate打印出执行的SQL
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE

info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@



